// generator.test.js — code generation tests for Pipethon.
//
// Each test compiles a Pipethon source string all the way through
// parse → analyze → optimize → generate and then asserts properties
// of the emitted JavaScript string.
//
// We check for key patterns rather than exact strings so that minor
// formatting changes don't break the suite.

import { describe, it } from "node:test"
import assert from "node:assert/strict"
import compile from "../src/compiler.js"

// Compile to JS and return the output string.
function js(source) {
  return compile(source, "js")
}

// Assert that the generated JS contains `pattern` (string or regex).
function has(source, pattern) {
  const output = js(source)
  if (typeof pattern === "string") {
    assert.ok(output.includes(pattern), `Expected output to include: ${pattern}\nGot:\n${output}`)
  } else {
    assert.match(output, pattern, `Expected output to match: ${pattern}\nGot:\n${output}`)
  }
}

describe("The generator", () => {

  // ── Prelude ───────────────────────────────────────────────────────────────

  it("emits the generated-by prelude comment", () => {
    has("42n |> print;", "Generated by Pipethon compiler")
  })

  // ── Let declarations ──────────────────────────────────────────────────────

  describe("let declarations", () => {
    it("emits const for a let binding", () => {
      has("let x = 42n;", /const x_\d+ = 42n/)
    })

    it("emits const for a string binding", () => {
      has('let s = "hello";', /const s_\d+ = "hello"/)
    })

    it("emits null for none", () => {
      has("let x: String? = none;", /null/)
    })
  })

  // ── Pipeline stages ───────────────────────────────────────────────────────

  describe("built-in pipe stages", () => {
    it("emits console.log for |> print", () => {
      has("42n |> print;", "console.log")
    })

    it("passes the value through after print (returns input)", () => {
      const out = js("42n |> print;")
      assert.ok(out.includes("console.log(42n)"), `Missing console.log call\nGot:\n${out}`)
    })

    it("emits .filter() for |> filter { ... }", () => {
      has("[1n, 2n, 3n] |> filter { int(n) if n > 1n => true _ => false };", ".filter(")
    })

    it("emits .map() for |> map { ... }", () => {
      has("[1n, 2n] |> map { int(n) => n * 2n _ => 0n };", ".map(")
    })

    it("passes through collect unchanged (already an array)", () => {
      // collect should not add extra wrapping — just return the array expression
      const out = js("[1n, 2n] |> collect;")
      assert.ok(!out.includes(".collect("), `Should not emit .collect() call\nGot:\n${out}`)
    })
  })

  // ── Pattern blocks ────────────────────────────────────────────────────────

  describe("pattern block emission", () => {
    it("emits an IIFE for a pattern block", () => {
      has('42n |> { int(n) => n _ => 0n };', /\(\(\(\$v\)/)
    })

    it("emits typeof check for int type pattern", () => {
      has('42n |> { int(n) => n _ => 0n };', 'typeof $v === "bigint"')
    })

    it("emits typeof check for float type pattern", () => {
      has('3.14 |> { float(f) => f _ => 0.0 };', 'typeof $v === "number"')
    })

    it("emits typeof check for string type pattern", () => {
      has('"hi" |> { string(s) => s _ => "" };', 'typeof $v === "string"')
    })

    it("emits typeof check for bool type pattern", () => {
      has('true |> { bool(b) => b _ => false };', 'typeof $v === "boolean"')
    })

    it("emits Array.isArray for list type pattern", () => {
      has('[1n] |> { list(xs) => xs _ => [] };', "Array.isArray($v)")
    })

    it("emits null check for none pattern", () => {
      has('let x: String? = none; x |> { some(s) => s none => "" };', "$v === null")
    })

    it("emits not-null check for some pattern", () => {
      has('let x: String? = none; x |> { some(s) => s none => "" };', "$v !== null")
    })

    it("emits === true for true literal pattern", () => {
      has('true |> { true => 1n _ => 0n };', "$v === true")
    })

    it("emits Array.isArray + length check for empty list pattern", () => {
      has('[] |> { [] => true _ => false };', ".length === 0")
    })

    it("emits Array.isArray + length >= 1 for head/tail pattern", () => {
      has('[1n, 2n] |> { [head, ...tail] => head _ => 0n };', ".length >= 1")
    })

    it("emits throw Error for no-match case", () => {
      has('42n |> { int(n) => n _ => 0n };', 'throw new Error("No match")')
    })

    it("emits hasOwnProperty check for object pattern", () => {
      has('{ name: "Alice" } |> { { name: n } => n _ => "" };', 'hasOwnProperty("name")')
    })

    it("emits a guard condition with &&", () => {
      has("[1n, 2n, 3n] |> filter { int(n) if n > 1n => true _ => false };", "&&")
    })
  })

  // ── Arithmetic and expressions ────────────────────────────────────────────

  describe("arithmetic expressions", () => {
    it("emits a parenthesised binary expression for addition", () => {
      has("let x = 2n + 3n;", "(2n + 3n)")
    })

    it("emits === for == operator (strict equality in JS)", () => {
      has("let x = 1n == 1n;", "===")
    })

    it("emits !== for != operator", () => {
      has("let x = 1n != 2n;", "!==")
    })

    it("emits unary minus for negation", () => {
      has("let x = -5n;", "(-5n)")
    })

    it("emits logical not", () => {
      has("let x = !true;", "(!true)")
    })
  })

  // ── Coalesce ──────────────────────────────────────────────────────────────

  describe("coalesce operator", () => {
    it("emits a ternary null-check for ??", () => {
      has('let x: String? = none; x ?? "default" |> print;', "!= null ?")
    })
  })

  // ── Method calls ──────────────────────────────────────────────────────────

  describe("method calls", () => {
    it("emits dot-method call syntax", () => {
      has('"hello" |> { string(s) => s.uppercase() _ => "" };', ".uppercase()")
    })

    it("emits method call with arguments", () => {
      has('"hello world" |> { string(s) => s.split(" ") _ => [] };', '.split(" ")')
    })
  })

  // ── LLM calls ─────────────────────────────────────────────────────────────

  describe("llm() calls", () => {
    it("emits an await __llm__() call for an LLM pipe stage", () => {
      has(
        '"hello" |> llm(model: "claude", prompt: "{input}") |> { some(s) => s none => "" };',
        "await __llm__("
      )
    })

    it("emits __llm__ with model argument", () => {
      has(
        '"hello" |> llm(model: "claude", prompt: "{input}") |> { some(s) => s none => "" };',
        "model:"
      )
    })
  })

  // ── Object and list literals ──────────────────────────────────────────────

  describe("object and list literals", () => {
    it("emits an array literal for a list", () => {
      has("[1n, 2n, 3n] |> print;", "[1n, 2n, 3n]")
    })

    it("emits an object literal with keys", () => {
      has('{ name: "Alice" } |> print;', 'name: "Alice"')
    })

    it("emits an empty array for an empty list", () => {
      has("[] |> print;", "[]")
    })
  })

  // ── Named pipelines ───────────────────────────────────────────────────────

  describe("named pipeline declarations", () => {
    it("emits a comment for a pipeline declaration", () => {
      has(
        "pipeline doubles = [1n, 2n] |> map { int(n) => n * 2n _ => 0n };",
        "// pipeline doubles declared"
      )
    })
  })

  // ── Multi-statement programs ──────────────────────────────────────────────

  describe("multi-statement programs", () => {
    it("emits multiple const declarations for multiple lets", () => {
      const out = js("let x = 1n; let y = 2n;")
      assert.match(out, /const x_\d+ = 1n/)
      assert.match(out, /const y_\d+ = 2n/)
    })

    it("emits both declaration and pipeline for mixed programs", () => {
      const out = js("let x = 42n; x |> print;")
      assert.match(out, /const x_\d+/)
      assert.ok(out.includes("console.log"), `Missing console.log\nGot:\n${out}`)
    })
  })
})